employeeid=int(input("Enter employee id  :"))
employeename=input("Enter the employee name  :")
employeesalary=float(input("Enter the salary  :"))
employeeaddress=input("Enter address")
married=eval(input("enter marriage status"))
print(employeeid)
print(employeename)
print(employeesalary)
print(employeeaddress)
print(married)